import Foundation

struct HealthKitTypeMapping {
    let displayString: String
    let workoutType: String

    static func map(activityTypeRawValue: UInt) -> HealthKitTypeMapping {
        switch activityTypeRawValue {
        case 1: return HealthKitTypeMapping(displayString: "American Football", workoutType: "Other")
        case 2: return HealthKitTypeMapping(displayString: "Archery", workoutType: "Other")
        case 3: return HealthKitTypeMapping(displayString: "Australian Rules Football", workoutType: "Other")
        case 4: return HealthKitTypeMapping(displayString: "Badminton", workoutType: "Other")
        case 5: return HealthKitTypeMapping(displayString: "Baseball", workoutType: "Other")
        case 6: return HealthKitTypeMapping(displayString: "Basketball", workoutType: "Other")
        case 7: return HealthKitTypeMapping(displayString: "Bowling", workoutType: "Other")
        case 8: return HealthKitTypeMapping(displayString: "Boxing", workoutType: "Other")
        case 9: return HealthKitTypeMapping(displayString: "Climbing", workoutType: "Other")
        case 10: return HealthKitTypeMapping(displayString: "Cricket", workoutType: "Other")
        case 11: return HealthKitTypeMapping(displayString: "Cross Training", workoutType: "HIIT")
        case 12: return HealthKitTypeMapping(displayString: "Curling", workoutType: "Other")
        case 13: return HealthKitTypeMapping(displayString: "Cycling", workoutType: "Cardio")
        case 16: return HealthKitTypeMapping(displayString: "Elliptical", workoutType: "Cardio")
        case 17: return HealthKitTypeMapping(displayString: "Equestrian Sports", workoutType: "Other")
        case 18: return HealthKitTypeMapping(displayString: "Fencing", workoutType: "Other")
        case 19: return HealthKitTypeMapping(displayString: "Fishing", workoutType: "Other")
        case 20: return HealthKitTypeMapping(displayString: "Functional Strength Training", workoutType: "Strength Training")
        case 21: return HealthKitTypeMapping(displayString: "Golf", workoutType: "Other")
        case 22: return HealthKitTypeMapping(displayString: "Gymnastics", workoutType: "Other")
        case 23: return HealthKitTypeMapping(displayString: "Handball", workoutType: "Other")
        case 24: return HealthKitTypeMapping(displayString: "Hiking", workoutType: "Cardio")
        case 25: return HealthKitTypeMapping(displayString: "Hockey", workoutType: "Other")
        case 26: return HealthKitTypeMapping(displayString: "Hunting", workoutType: "Other")
        case 27: return HealthKitTypeMapping(displayString: "Lacrosse", workoutType: "Other")
        case 28: return HealthKitTypeMapping(displayString: "Martial Arts", workoutType: "Other")
        case 29: return HealthKitTypeMapping(displayString: "Mind and Body", workoutType: "Other")
        case 31: return HealthKitTypeMapping(displayString: "Paddle Sports", workoutType: "Cardio")
        case 32: return HealthKitTypeMapping(displayString: "Play", workoutType: "Other")
        case 33: return HealthKitTypeMapping(displayString: "Preparation and Recovery", workoutType: "Other")
        case 34: return HealthKitTypeMapping(displayString: "Racquetball", workoutType: "Other")
        case 35: return HealthKitTypeMapping(displayString: "Rowing", workoutType: "Cardio")
        case 36: return HealthKitTypeMapping(displayString: "Rugby", workoutType: "Other")
        case 37: return HealthKitTypeMapping(displayString: "Running", workoutType: "Cardio")
        case 38: return HealthKitTypeMapping(displayString: "Sailing", workoutType: "Other")
        case 39: return HealthKitTypeMapping(displayString: "Skating Sports", workoutType: "Cardio")
        case 40: return HealthKitTypeMapping(displayString: "Snow Sports", workoutType: "Cardio")
        case 41: return HealthKitTypeMapping(displayString: "Soccer", workoutType: "Other")
        case 42: return HealthKitTypeMapping(displayString: "Softball", workoutType: "Other")
        case 43: return HealthKitTypeMapping(displayString: "Squash", workoutType: "Other")
        case 44: return HealthKitTypeMapping(displayString: "Stair Climbing", workoutType: "Cardio")
        case 45: return HealthKitTypeMapping(displayString: "Surfing", workoutType: "Cardio")
        case 46: return HealthKitTypeMapping(displayString: "Swimming", workoutType: "Cardio")
        case 47: return HealthKitTypeMapping(displayString: "Table Tennis", workoutType: "Other")
        case 48: return HealthKitTypeMapping(displayString: "Tennis", workoutType: "Other")
        case 49: return HealthKitTypeMapping(displayString: "Track and Field", workoutType: "Cardio")
        case 50: return HealthKitTypeMapping(displayString: "Traditional Strength Training", workoutType: "Strength Training")
        case 51: return HealthKitTypeMapping(displayString: "Volleyball", workoutType: "Other")
        case 52: return HealthKitTypeMapping(displayString: "Walking", workoutType: "Cardio")
        case 53: return HealthKitTypeMapping(displayString: "Water Fitness", workoutType: "Cardio")
        case 54: return HealthKitTypeMapping(displayString: "Water Polo", workoutType: "Other")
        case 55: return HealthKitTypeMapping(displayString: "Water Sports", workoutType: "Cardio")
        case 56: return HealthKitTypeMapping(displayString: "Wrestling", workoutType: "Other")
        case 57: return HealthKitTypeMapping(displayString: "Yoga", workoutType: "Yoga")
        case 58: return HealthKitTypeMapping(displayString: "Barre", workoutType: "Other")
        case 59: return HealthKitTypeMapping(displayString: "Core Training", workoutType: "Strength Training")
        case 60: return HealthKitTypeMapping(displayString: "Cross-Country Skiing", workoutType: "Cardio")
        case 61: return HealthKitTypeMapping(displayString: "Downhill Skiing", workoutType: "Cardio")
        case 62: return HealthKitTypeMapping(displayString: "Flexibility", workoutType: "Other")
        case 63: return HealthKitTypeMapping(displayString: "HIIT", workoutType: "HIIT")
        case 64: return HealthKitTypeMapping(displayString: "Jump Rope", workoutType: "Other")
        case 65: return HealthKitTypeMapping(displayString: "Kickboxing", workoutType: "Other")
        case 66: return HealthKitTypeMapping(displayString: "Pilates", workoutType: "Pilates")
        case 67: return HealthKitTypeMapping(displayString: "Snowboarding", workoutType: "Cardio")
        case 68: return HealthKitTypeMapping(displayString: "Stairs", workoutType: "Cardio")
        case 69: return HealthKitTypeMapping(displayString: "Step Training", workoutType: "Cardio")
        case 70: return HealthKitTypeMapping(displayString: "Wheelchair Walk Pace", workoutType: "Cardio")
        case 71: return HealthKitTypeMapping(displayString: "Wheelchair Run Pace", workoutType: "Cardio")
        case 72: return HealthKitTypeMapping(displayString: "Tai Chi", workoutType: "Other")
        case 73: return HealthKitTypeMapping(displayString: "Mixed Cardio", workoutType: "Cardio")
        case 74: return HealthKitTypeMapping(displayString: "Hand Cycling", workoutType: "Cardio")
        case 75: return HealthKitTypeMapping(displayString: "Disc Sports", workoutType: "Other")
        case 76: return HealthKitTypeMapping(displayString: "Fitness Gaming", workoutType: "HIIT")
        case 77: return HealthKitTypeMapping(displayString: "Cardio Dance", workoutType: "Cardio")
        case 78: return HealthKitTypeMapping(displayString: "Social Dance", workoutType: "Cardio")
        case 79: return HealthKitTypeMapping(displayString: "Pickleball", workoutType: "Other")
        case 80: return HealthKitTypeMapping(displayString: "Cooldown", workoutType: "Other")
        case 81: return HealthKitTypeMapping(displayString: "Swim Bike Run", workoutType: "Cardio")
        case 82: return HealthKitTypeMapping(displayString: "Transition", workoutType: "Cardio")
        case 83: return HealthKitTypeMapping(displayString: "Underwater Diving", workoutType: "Other")
        case 84: return HealthKitTypeMapping(displayString: "Mixed Metabolic Cardio Training", workoutType: "Cardio")
        case 3000: return HealthKitTypeMapping(displayString: "Other", workoutType: "Other")
        default: return HealthKitTypeMapping(displayString: "Activity \(activityTypeRawValue)", workoutType: "Other")
        }
    }
}
